### ISSUE TITLE
"docker build . --tag rinocchio-bench" fails

### ISSUE THREAD

**Issue by ShaneKosieradzki** [zkFHE/ringSNARK#5]
When running `docker build` for the rinocchio-bench the cmake script fails on step (12/13) on the `RUN cmake..` subcommand.

See screenshot below:

![image](https://github.com/zkFHE/ringSNARK/assets/42522906/9ad2bacf-7f09-48bf-adbd-d33c0d251822)

![image](https://github.com/zkFHE/ringSNARK/assets/42522906/f10fccc6-5b1c-4c5d-b5a2-80aa6bf92a2a)

**Comment by cknabs** [comment]
Hi, did you run `git submodule init && git submodule update --recursive` before calling `docker build`? 

We're using git submodules to pull in some dependencies, and these submodules need to be present for the build to succeed (I clarified the README accordingly).
